services:
  app:
    build: .
    env_file:
      - .env.development
    environment:
      APP_ENV: production
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    restart: unless-stopped

version: "3.9"
